import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-100 text-neutral-900`}>
        <header className="sticky top-0 z-50 w-full bg-[#3f6f0d] text-white shadow">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-12 items-center justify-between">
              <div className="flex items-center gap-2">
                <a href="/instructions" className="font-semibold">Instructions et Aide</a>
                <nav className="hidden md:flex items-center gap-2 text-sm">
                  {Array.from({ length: 8 }).map((_, i) => (
                    <a
                      key={i}
                      className="rounded bg-[#2f550a] px-2 py-0.5 hover:bg-[#274707]"
                      href={`/ex${i + 1}`}
                    >
                      Ex {i + 1}
                    </a>
                  ))}
                </nav>
              </div>
              <div className="text-xs opacity-90">Termine dans : 1h 59m</div>
            </div>
          </div>
        </header>
        <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
